# Generated by Django 4.2.1 on 2023-05-26 15:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerary',
            name='finishData',
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='startData',
        ),
        migrations.AddField(
            model_name='itinerary',
            name='finishDate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itinerary',
            name='startDate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
